---
apiVersion: v1
kind: ConfigMap
metadata:
  name: songlist-config-init
  namespace: songlist
data:
  VAULT_REQUEST: |
    {
      "vault_request": [{
        "mount": "lavacro",
        "path": "prod/database/postgresql",
        "items": [{
          "key": "password",
          "label": "spring.datasource.password"
        }]
      }],
      "file_path": "/var/tmp/vault/vault.properties"
    }
  MOUNT_PATH: "/var/tmp/vault"
  VAULT_ADDR: "http://vault.lavacro.net:8201"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: songlist-config-app
  namespace: songlist
data:
  SPRING_DATASOURCE_USERNAME: "david"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://prod-db.lavacro.net:5432/songs?reWriteBatchedInserts=true"
  SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/var/tmp/vault/vault.properties"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: songlist-app
  labels:
    app: songlist
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      labels:
        app: songlist
        tier: web
    spec:
      volumes:
        - name: vault-token
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
      initContainers:
      - name: vault-retrieve
        image: "registry:5000/govault:1.0.0"
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: songlist-config-init
        - secretRef:
            name: songlist-secrets
        volumeMounts:
        - name: vault-token
          mountPath: "/var/tmp/vault"
      containers:
      - name: songlist
        image: "registry:5000/songlist:1.22.0"
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: songlist-config-app
        volumeMounts:
        - name: vault-token
          mountPath: "/var/tmp/vault"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "500m" # 0.5 CPU
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8444
          timeoutSeconds: 60
          #          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8444
          timeoutSeconds: 3
          initialDelaySeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: songlist-service
spec:
  selector:
    app: songlist
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8444
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: songlist-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: songlist.cloud.lavacro.net
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: songlist-service
            port:
              number: 80
